### ISSUE TITLE
我发现我一直template拼的是错的

### ISSUE THREAD

**Issue by siyuanwu99** [qyxf/Tutorials#2]
。。。。。。

**Comment by xjtu-blacksmith** [comment]
优秀！

**Comment by niwakoki** [comment]
别忘初衷

**Comment by gxf1212** [comment]
别忘初衷。。

**Comment by niwakoki** [comment]
别忘初衷皮卡皮卡皮卡丘
(〃'▽'〃)(｀・ω・´)(〃´-ω･) (>ω･* )ﾉ(￣.￣)o(￣▽￣)ｄ （￣︶￣）↗ヾ(=･ω･=)od(´ω｀*)ヾ(ｏ･ω･)ﾉφ(>ω<*) (*/ω＼*)(*･ω< )  (=´ω｀=)╰(￣▽￣)╭╮(￣▽￣)╭

-------------------------------------
我是大一萌新啊哈哈哈哈霍霍

**Comment by niwakoki** [comment]
can i discus with u in this comment

**Comment by niwakoki** [comment]
which is close and reopen?
